hmcts/ccd-test-stubs-service

wiremock/mappings/ccd/callback_returning_simulated_completed_noc_request.json

[ACA-68](https://tools.hmcts.net/jira/browse/ACA-68) _"3.3.6 NoCRequest API"_
Added a callback stub to simulate an approved NOC request that has been processed by `CheckForNoCApproval` and `ApplyNoCDecision`.
This test stub should no longer be required once these APIs are ready.
```
[ ] Yes
[x] No
```

ACA-68: Callback to simulate completed NOC request

---

wiremock/mappings/ccd/callback_returning_simulated_completed_noc_request.json

[ACA-68](https://tools.hmcts.net/jira/browse/ACA-68) _"3.3.6 NoCRequest API"_
[RDM-9893](https://tools.hmcts.net/jira/browse/RDM-9893) _"Organisation base type incorrectly contains a 'Name' Field"_
Update the callback stub that simulates an approved NOC request that has been processed by `CheckForNoCApproval` and `ApplyNoCDecision`.   i.e. update OrganisationName references in preparation for:
* RDM-9893 - Remove OrganisationName references hmcts/aac-manage-case-assignment#136
This test stub should no longer be required once these APIs are ready.
```
[ ] Yes
[ ] No
```

ACA-68: Update simulate completed NOC request

---

build.gradle
dependency-check-suppressions.xml

CCD-1861 (https://tools.hmcts.net/jira/browse/CCD-1861)
- Resolved vulnerability in use of Jakarta EL version 3.0.3 by adding
dependency on version 4.0.1 to build.gradle file.
- Removed corresponding suppression from
dependency-check-suppressions.xml.
```
[ ] Yes
[x] No
```

Resolve CVE-2021-28170

---

build.gradle
dependency-check-suppressions.xml

CCD-2115 (https://tools.hmcts.net/jira/browse/CCD-2115)
- Updated build.gradle. Set value of tomcatVersion property to 9.0.54 to resolve CVE-2021-42340.
- Removed suppression of CVE-2021-42340 from dependency-check-suppressions.xml.
```
[ ] Yes
[x] No
```

CCD-2115: Address CVE-2021-42340

---

wiremock/mappings/ccd/callback_unmodified.json

Changed the name of the callback 'callback_about_to_start_ttl_unmodified' to 'callback_unmodified', so this can be reused in various requests.
```
[ ] Yes
[X] No
```

Making callback name more generic

---

build.gradle
dependency-check-suppressions.xml

CCD-2141 (https://tools.hmcts.net/jira/browse/CCD-2141)
- Updated build.gradle. Set value of override of spring-framework.version property to 5.3.12 to address CVE-2021-22096.
- Removed temporary suppression of CVE-2021-22096 from dependency-check-suppressions.xml
```
[ ] Yes
[x] No
```

CCD-2141: Address CVE-2021-22096

---

dependency-check-suppressions.xml

CCD-2231 (https://tools.hmcts.net/jira/browse/CCD-2231)
Changed CVE suppression dates in dependency-check-suppressions.xml to 2022-01-25.
```
[ ] Yes
[x] No
```

CCD-2231: Updated CVE suppression dates

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3269
Upgrading tomcat version to 9.0.63.
The documentation of Apache Tomcat 10.1.0-M1 to 10.1.0-M14, 10.0.0-M1 to 10.0.20, 9.0.13 to 9.0.62 and 8.5.38 to 8.5.78 for the EncryptInterceptor incorrectly stated it enabled Tomcat clustering to run over an untrusted network. This was not correct.
```
[ ] Yes
[x ] No
```

CVE-2022-29885: ccd-test-stubs-service fix

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3431
Update dependency-check-suppressions.xml added temporary suppression for CVE-2022-34305
```
[ ] Yes
[X] No
```

Update dependency-check-suppressions.xml added temporary suppression for CVE-2022-34305

---

charts/ccd-test-stubs-service/Chart.yaml
src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/WireMockServerConfig.java
wiremock/mappings/hmc/ccd/getCcdCaseById.json
wiremock/mappings/hmc/hearing/amendRequestHearing.json
wiremock/mappings/hmc/hearing/createRequestHearing.json
wiremock/mappings/hmc/hearing/deleteRequestHearing.json
wiremock/mappings/hmc/linkedHearingGroup/createLinkedHearingGroup.json
wiremock/mappings/hmc/linkedHearingGroup/deleteLinkedHearingGroup.json
wiremock/mappings/hmc/linkedHearingGroup/updateLinkedHearingGroup.json

https://tools.hmcts.net/jira/browse/HMAN-311
Mock calls to HMI/FH/ListAssist
A test stub will need to be created to be able to mock response from FH which is an external team call 
Endpoints are
[Create, Delete, Amend Hearing](https://github.com/hmcts/hmc-hmi-outbound-adapter/blob/master/src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/HearingManagementInterfaceApiClient.java)
[Create, Update, Delete Linked group](https://github.com/hmcts/hmc-cft-hearing-service/blob/master/src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/HearingManagementInterfaceApiClient.java)
[Generate Token](https://github.com/hmcts/hmc-cft-hearing-service/blob/master/src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/ActiveDirectoryApiClient.java)
**Does this PR introduce a breaking …

HMAN-311 - Add new HMC stubs

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3431
CVE-2022-34305 tomcat upgrade
```
[ ] Yes
[ x] No
```

CCD-3431 CVE-2022-34305 tomcat upgrade, suppression removed

---

wiremock/mappings/ccd/callback_nextHearingDate.json
wiremock/mappings/ccd/callback_nextHearingDateIsInPast.json

[HMAN-368](https://tools.hmcts.net/jira/browse/HMAN-368) _"Ccd Def store definition changes"_
Add next hearing date callbacks
> NB: these callbacks are referenced in hmcts/ccd-test-definitions#53 and used in FTAs:
> * hmcts/ccd-next-hearing-date-updater#38
> * hmcts/ccd-next-hearing-date-updater#53
```
[ ] Yes
[X] No
```

HMAN-368 - Add next hearing date callbacks

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3658
Removed suppression for CVE-2022-25857 and updated build.gradle with ext['snakeyaml.version'] = '1.31'
```
[ ] Yes
[X] No
```

CCD-3658-CVE-2022-25857-fix

---

README.md
wiremock/mappings/ccd/callback_nextHearingDate.json
wiremock/mappings/ccd/callback_nextHearingDateClear.json
wiremock/mappings/ccd/callback_nextHearingDateIsNull.json
wiremock/mappings/ccd/callback_nextHearingIdIsNull.json

[HMAN-342](https://tools.hmcts.net/jira/browse/HMAN-342) _"BEFTA for NextHearingDate"_
* [HMAN-381](https://tools.hmcts.net/jira/browse/HMAN-381) _"FTAs for CSV Processing"_ (sub-task)
* [HMAN-382](https://tools.hmcts.net/jira/browse/HMAN-382) _"FTAs for Elastic Search processing"_ (sub-task)
Extra callbacks to support extra functional test automation scripts in hmcts/ccd-next-hearing-date-updater#94
> Test PRs in main repos: 
> * hmcts/ccd-definition-store-api#1315
> * hmcts/ccd-data-store-api#2154
```
[ ] Yes
[x] No
```

HMAN-342 add extra Next Hearing Date callbacks

---

.travis.yml

https://tools.hmcts.net/jira/browse/CCD-4476
CCD-4476 : changed reform-api-docs to cnp-api-docs
```
[ ] Yes
[X] No
```

CCD-4476 : changed reform-api-docs to cnp-api-docs

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-4599
CCD-4599 : Update build.gradle (Bump sonaqube version to 2.7), to fix broken downstream link to sonarcloud
```
[ ] Yes
[X] No
```

CCD-4599 : Update build.gradle (Bump sonaqube version to 2.7)

---

build.gradle
dependency-check-suppressions.xml
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/CCD-4739
CCD-4739 : Fix Fix CVE-2023-20860, CVE-2023-20861, CVE-2023-20863 (bumped versions of gradle, springframework, springsecurity)
```
[ ] Yes
[X] No
```

CCD-4739 : Fix Fix CVE-2023-20860, CVE-2023-20861, CVE-2023-20863 (bumped versions of gradle, springframework, springsecurity)

---

.github/renovate.json
Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CCD-4845
Renovate config is now mandatory in every repo extending default org level config without using enabledManagers.
```
[ ] Yes
[x] No
```

CCD-4845 renovate config

---

build.gradle
charts/ccd-test-stubs-service/Chart.yaml
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4970
updated gauva library and removed suppression
```
[ ] Yes
[X] No
```

CCD-4970 : Fix CVE-2020-8908

---

build.gradle
dependency-check-suppressions.xml

CCD-4969
bumped spring-security.version to v5.7.10
```
[ ] Yes
[X] No
```

CCD-4969: bumped spring-security.version to v5.7.10

---

build.gradle
dependency-check-suppressions.xml

[CCD-5205](https://tools.hmcts.net/jira/browse/CCD-5205)
Upped version of wiremock to resolve CVE. Both CVEs CVE-2023-41327 and CVE-2023-41329 are for the same issue so raised separate PRs to remove the suppressions.
```
[ ] Yes
[X] No
```

Updating wiremock as there are 2 seperate CVEs for this issue

---

src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/util/HeadersProvider.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/util/HttpHeadersProvider.java
wiremock/mappings/ccd/callback_about_to_submit.json
wiremock/mappings/ccd/callback_about_to_submit_party_info_modified.json
wiremock/mappings/ccd/callback_submitted.json

https://tools.hmcts.net/jira/browse/CCD-5367
Add 'Client-Context' header for aboutToSubmit and submitted callbacks
```
[ ] Yes
[x] No
```

CCD-5367 Task Completion - CCD Send Header from callback response to EXUI
