Jenkinsfile_CNP

RDM-4742 - configure sandbox pipeline

---

src/functionalTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/StubFunctionalTest.java
src/smokeTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/StubSmokeTest.java

RDM-4742 - configure master pipeline

---

src/functionalTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/StubFunctionalTest.java
src/smokeTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/StubSmokeTest.java

RDM-4742 - relax SSL validation for tests

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/WireMockServerConfig.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/WireMockServerConfigTest.java

RDM-4742 - fix mappings path

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java
src/integrationTest/resources/application.yaml

RDM-4742 - fix integration test

---

src/main/resources/application.yaml

RDM-4742 - change wiremock port

---

docker-compose.yml

RDM-4742 - configure new azure acr for docker builds

---

dependency-check-suppressions.xml
wiremock/mappings/aat_mid_event_dynamiclist.json

https://tools.hmcts.net/jira/browse/RDM-4648
We needed to add new payload for dynamiclist 
```
[ ] Yes
[ ] No
```

RDM - 4648 - Added new dynamic list payload for mid event

---

src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/WireMockServerConfigTest.java

sonar coverage fix

---

build.gradle
config/owasp/suppressions.xml
dependency-check-suppressions.xml

added suppression

---

charts/ccd-test-stubs-service/Chart.yaml
charts/ccd-test-stubs-service/requirements.yaml
charts/ccd-test-stubs-service/values.yaml

update chart, fix repo

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-7407
```
[ ] Yes
[x] No
```

Resolve CVE-2020-5398

---

charts/ccd-test-stubs-service/Chart.yaml
charts/ccd-test-stubs-service/requirements.yaml

RDM-7389 bump versions

---

Jenkinsfile_CNP

RDM-7389 enable AKS

---

charts/ccd-test-stubs-service/Chart.yaml
charts/ccd-test-stubs-service/values.yaml

RDM-7389 add ingress

---

Jenkinsfile_CNP

RDM-7389 disableLegacyDeploymentOnAAT

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/variables.tf

RDM-7389 Rm aat ASE

---

charts/ccd-test-stubs-service/Chart.yaml
charts/ccd-test-stubs-service/values.yaml

RDM-7496 rm liveness

---

charts/ccd-test-stubs-service/Chart.yaml
charts/ccd-test-stubs-service/requirements.yaml

RDM-7867-Update-base-chart

---

infrastructure/main.tf
infrastructure/variables.tf

Rdm-8175-rm-TF

---

wiremock/mappings/idam/idam_well-known_openid_configuration.json

Fixing idam stub to inline with spring-security bump to 5.3.2.RELEASE

---

Jenkinsfile_CNP
README.md
build.gradle
infrastructure/main.tf
infrastructure/variables.tf
src/integrationTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java
src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/ApplicationConfig.java
src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/IdamUserInfo.java
src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java
src/main/resources/userInfoOverrideRequestTemplate.json
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java

RDM-8816: Runtime stubbing of idam user info

---

build.gradle
dependency-check-suppressions.xml
wiremock/mappings/prd/prd_organisation_users.json

[RDM-9118](https://tools.hmcts.net/jira/browse/RDM-9118) _"Increment Assigned User Count FTA organisation adjustment"_
[RDM-8842](https://tools.hmcts.net/jira/browse/RDM-8842) _"Increment Assigned User Count of Cases when Assigned to Users"_
Increment Assigned User Count FTA organisation adjustment:
* load organisation data from PRD or test stub.
```
[ ] Yes
[x] No
```

RDM-9118 FTA organisation adjustment for RDM-8842

---

.github/renovate.json
charts/ccd-test-stubs-service/Chart.yaml
charts/ccd-test-stubs-service/requirements.yaml
dependency-check-suppressions.xml

Rdm 8784 helm renovate

---

dependency-check-suppressions.xml
infrastructure/variables.tf

temporarily suppress cve flag
```
[ ] Yes
[X] No
```

suppress temporarily and fix tf changes

---

dependency-check-suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java
src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java

https://tools.hmcts.net/jira/browse/RDM-10078
https://tools.hmcts.net/jira/browse/RDM-9877
Support xui on ccd stub service
```
[ ] Yes
[X ] No
```

RDM-9877: Support EXUI on CCD IDAM Stub Service

---

build.gradle

Supress coverage on WireMockServerConfig.java

---

dependency-check-suppressions.xml
wiremock/mappings/ccd/callback_all_dynamic_lists.json
wiremock/mappings/ccd/callback_collection_dynamic_multi_select_list.json
wiremock/mappings/ccd/callback_collection_dynamic_radio_list.json
wiremock/mappings/ccd/callback_complex_dynamic_lists.json
wiremock/mappings/ccd/callback_dynamic_multi_select_list.json
wiremock/mappings/ccd/callback_dynamic_radio_list.json

https://tools.hmcts.net/jira/browse/RDM-10874
Add call back mocks for dynamic radio list and dynamic multi select list
```
[ ] Yes
[ X] No
```

RDM-10874: call back mappings added for dynamic lists

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-11435
CVE-2021-22112 (Test Stub Service)
```
[ ] Yes
[X] No
```

RDM-11435 CVE-2021-22112 (Test Stub Service)

---

charts/ccd-test-stubs-service/Chart.yaml

https://tools.hmcts.net/jira/browse/RDM-12054
Upgrade Base Chart Versions (Java & Nodejs)
```
[ ] Yes
[X] No
```

RDM-12054 Upgrade Base Chart Versions (Java & Nodejs)

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-12200?filter=-1
CVE-2021-29425 (Test Stubs Service)
```
[ ] Yes
[X] No
```

RDM-12200 Fix CVE's Test Stubs Service

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-1232
CVE-2021-22112 (Test Stubs Service)
```
[ ] Yes
[x] No
```

CCD-1232 CVE-2021-22112 (Test Stubs Service)

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-1278
CVE-2021-22118 in Test Stubs Service
```
[ ] Yes
[x] No
```

CCD-1278 CVE-2021-22118 in Test Stubs Service

---

dependency-check-suppressions.xml

tidy up dependency-check-suppressions.xml

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-1567
```
[ ] Yes
[x] No
```

suppress CVE

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-1567
fix for CVE-2021-27568
```
[ ] Yes
[ ] No
```

fix for CVE-2021-27568

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-1643
fix for CVE-2021-33037
```
[ ] Yes
[x] No
```

fix for CVE-2021-33037

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/CCD-1664
integrate fortify scan into nightly pipelines
```
[ ] Yes
[X] No
```

integrate fortify scan into nightly pipelines

---

dependency-check-suppressions.xml

Suppress CVE-2021-28170
```
[ ] Yes
[ ] No
```

Suppress CVE-2021-28170

---

build.gradle
wiremock/mappings/refdata/get_building_locations.json
wiremock/mappings/refdata/get_org_services.json

https://tools.hmcts.net/jira/browse/RDM-12683
Add court location reference data
```
[ ] Yes
[x] No
```

RDM-12683 Add location reference data

---

dependency-check-suppressions.xml

CCD-1993 (https://tools.hmcts.net/jira/browse/CCD-1993)
Updated CVE suppression dates in dependency-check-suppressions.xml to 25/10/2021
```
[ ] Yes
[x] No
```

Updated CVE suppression dates in dependency-check-suppressions.xml

---

wiremock/mappings/ccd/callback_mid_event_override_ttl_modified.json
wiremock/mappings/ccd/callback_mid_event_suspended_ttl_modified.json
wiremock/mappings/ccd/callback_mid_event_system_ttl_modified.json

https://tools.hmcts.net/jira/browse/RDM-12857
add mid-event callback stubs for modifying ttl data
```
[ ] Yes
[x] No
```

RDM-12857 - add mid-event callback stubs for modifying ttl data

---

wiremock/mappings/ccd/callback_get_case.json

https://tools.hmcts.net/jira/browse/RDM-12853
Stubbing new GetCaseCallback callback endpoint
```
[ ] Yes
[X ] No
```

RDM-12853 Mock GetCaseCallback

---

wiremock/mappings/ccd/callback_about_to_submit_party_info_modified.json

This callback is used by one event of FT_GlobalSearch to populate the case data.
```
[ ] Yes
[x] No
```

RDM-12764 - Callback to populate case details for GlobalSearch case type

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2357
Amend suppression date by 1 month
```
[ ] Yes
[ X] No
```

Amend suppression date by 1 month

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties
dependency-check-suppressions.xml
wiremock/mappings/ccd/callback_about_to_submit_party_info_modified.json

The DateOfBirth and DateOfDeath variables have changed to dateOfBirth and dateOfDeath in the new definition file for GS.
This PR amends the names in the /callback_about_to_submit_party_info_modified used by F-1005 in data-store.
```
[] Yes
[X] No
```

Amending variable names in /callback_about_to_submit_party_info_modified

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2589
Suppressing:
CVE-2021-22060, CVE-2022-23181, CVE-2021-42550, CVE-2021-44832
```
[ ] Yes
[ x] No
```

CCD-2589: Suppress CVE pending investigation

---

charts/ccd-test-stubs-service/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```

update heml version

---

dependency-check-suppressions.xml

Also added dates if they do not have them
https://tools.hmcts.net/jira/browse/CCD-2497
Amended the CVE suppression date by a month
```
[ ] Yes
[ X] No
```

Amend Suppression Dates 

---

charts/ccd-test-stubs-service/Chart.yaml

Upgrade to Latest Base Helm Charts

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-2927
```
[ ] Yes
[ ] No
```

spring-framework.version update to 5.3.18 from 5.3.15

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2826
```
[ ] Yes
[ ] No
```

jackson.version update for CVE-2020-36518

---

dependency-check-suppressions.xml

Suppression for spring-core-5.3.18.jar relate dependency check failure.
```
[ ] Yes
[ x] No
```

spring-core-5.3.18.jar dependency suppression

---

src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java

https://tools.hmcts.net/jira/browse/CCD-2932
CCD Docker image stability local development
```
[ ] Yes
[x] No
```

CCD-2932 initial commit

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3292
```
[ ] Yes
[x] No
```

suppression of CVE-2022-22970,CVE-2022-22971

---

Dockerfile

https://tools.hmcts.net/jira/browse/CCD-3355
Add "USER hmcts" to Dockerfile  ,  (similar to Jira ticket CCD-3203  /  pull request #1987)
```
[ ] Yes
[x] No
```

CCD-3355: Dockerfile Fortify fix

---

charts/ccd-test-stubs-service/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-3376
AKS is failing in Preview Env - update ccd charts
```
[ ] Yes
[x] No
```

CCD-3376 Update java chart version

---

charts/ccd-test-stubs-service/Chart.yaml
dependency-check-suppressions.xml

n/a
Add comment to suppressions.xml
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

Add comment to suppressions.xml

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3449
CCD-3449 : Update dependency-check-suppressions.xml (CVE-2022-33915)
```
[ ] Yes
[X] No
```

CCD-3449 : Update dependency-check-suppressions.xml (CVE-2022-33915)

---

charts/ccd-test-stubs-service/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-3434
Upgrade Java, postgresql and redis configurations
```
[ ] Yes
[x] No
```

CCD-3434 Upgrade Java, postgresql and redis configurations

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-965
CCD-965: Remove Temporary Sonar Exclusions ccd-test-stubs-service
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

CCD-965: Remove Temporary Sonar Exclusions ccd-test-stubs-service

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3524
Fixed
```
[ ] Yes
[x] No
```

CCD-3524: Fix for CVE-2021-22119

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3511
CVE-2020-15522
```
[ ] Yes
[ x] No
```

CCD-3511 CVE-2020-15522 bouncycastle 1.70 dependency added

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-3563
Remove Version Number
```
[ ] Yes
[ X] No
```

Remove version number

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3820
CVE-2022-42889
```
[ ] Yes
[ x] No
```

CCD-3820 CVE-2022-42889 suppression

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3820
updated handlebars to v4.3.1, removed temporary suppression
```
[ ] Yes
[X] No
```

CCD-3820:CVE-2022-42889-Fix

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3918
```
[ ] Yes
[ x] No
```

CCD-3918 CVE-2022-42252

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3917
Upgrade to Spring Security
- CVE-2022-31690 CVE-2022-31692
```
[ ] Yes
[ x] No
```

CCD-3917 Spring Security Upgrade

---

.github/workflows/dependency-check.yml
build.gradle
dependency-check-suppressions.xml
gradle/suppress.gradle

https://tools.hmcts.net/jira/browse/CCD-3533
Add a cron job to build the pipeline regularly
Clean up dependency-check-suppressions.xml
- Comments are stripped by the cleanSuppressions task which runs after the suppressCVEs task
```
[ ] Yes
[ x] No
```

CCD-3533 Add suppressCves task 

---

charts/ccd-test-stubs-service/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-4017
Upgrade base charts for Jenkins enhancements
```
[ ] Yes
[x ] No
```

Ccd 4017 helm chart upgrades

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4312
CVE-2022-45143 Tomcat Upgrade
```
[ ] Yes
[x ] No
```

CCD-4312 CVE-2022-45143 Tomcat Upgrade

---

charts/ccd-test-stubs-service/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```

CCD-4317 Upgrade base charts

---

.github/renovate.json
build.gradle

CCD-4598 Update renovate.json

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-4949
Fix - Versions below java-logging: 6.0.1
```
[ ] Yes
[ ] No
```

CCD-4949:Fix - Versions below java-logging: 6.0.1

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/CCD-5018
```
[ ] Yes
[ ] No
```

add environment variable for jwt expiration

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4994
bumped jetty version to 9.4.53
```
[ ] Yes
[X] No
```

CCD-4994 : Fix-CVE-2023-36478 

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4604
Removed the notes relating to 20873 as this has been resolved under 20883
```
[ ] Yes
[X] No
```

CVE fixes 160124

---

acb.tpl.yaml
build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5045

CCD-5045 : Fix acb entries to fix timeout issue

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5136
Changes made to resolve CVE
```
[ ] Yes
[x] No
```

CVE fixes 010224

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4973
Cleanup dependencies file, remove reference to CVE-2023-42794
```
[ ] Yes
[ ] No
```

Cleanup dependencies file

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5160
CCD-5160: bumped jackson.version to 2.16.0
```
[ ] Yes
[ x] No
```

CCD-5160: bumped jackson.version to 2.16.0

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5204
Updated the version of wire mock to resolve CVE
```
[ ] Yes
[X] No
```

CCD-5204  updated wiremock version to resolve CVE

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5201
Updated Spring Security version to resolve CVE.
```
[ ] Yes
[X] No
```

CCD-5201 CVE fixes 080324

---

src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java

NA
unit tests for sonar code coverage issues detected in pipeline
```
[ ] Yes
[X] No
```

add test for sonar coverage

---

src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java

NA
Fix sonar failure in master branch
```
[ ] Yes
[X] No
```

Fix sonar coverage 1

---

src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java
src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java

Add code coverage
```
[ ] Yes
[x] No
```

Fix sonar coverage

---

infrastructure/state.tf

https://tools.hmcts.net/jira/browse/CME-314
```
[ ] Yes
[ x] No
```

CME-314: Update azurerm

---

wiremock/mappings/ccd/callback_about_to_start_ttl_modified_null.json
wiremock/mappings/ccd/callback_about_to_submit_ttl_modified_null.json
wiremock/mappings/ccd/callback_mid_event_override_ttl_modified_null.json
wiremock/mappings/ccd/callback_ttl_empty.json

CME-110: Apply NullifyByDefault to a field when it is set to True/Yes

---

charts/ccd-test-stubs-service/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```

CCD-6193 update base chart version

---

build.gradle

https://tools.hmcts.net/jira/browse/CME-676
Replaced JitPack with Azure Artifacts and upgraded Fortify client
```
[ ] Yes
[X] No
```

CME-676 Replaced JitPack with Azure Artifacts
